# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0002_auto_20180302_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(blank=True, upload_to='post_images')),
            ],
        ),
    ]
