# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='userPicture',
        ),
    ]
