# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0004_auto_20180302_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
