# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0005_auto_20180302_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 15, 27, 20, 959000)),
        ),
    ]
