# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0006_post_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
