# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0007_auto_20180306_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pethub.UserProfile'),
        ),
    ]
