# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethub', '0011_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', help_text="Please enter all the tags you'd like to include here, like this:\n cats, cute, furry", max_length=100),
        ),
    ]
